// Mocks generated by Mockito 5.4.6 from annotations
// in network_status_service/test/network/presentation/connectivity_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:network_status_service/network/domain/i_network_info.dart'
    as _i2;
import 'package:network_status_service/network/domain/network_status.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [INetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkInfo extends _i1.Mock implements _i2.INetworkInfo {
  MockINetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.NetworkStatus> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i3.Stream<_i4.NetworkStatus>.empty(),
          )
          as _i3.Stream<_i4.NetworkStatus>);

  @override
  _i3.Future<_i4.NetworkStatus> get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.Future<_i4.NetworkStatus>.value(
              _i4.NetworkStatus.uninitialized,
            ),
          )
          as _i3.Future<_i4.NetworkStatus>);

  @override
  bool get hasInternetConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasInternetConnection),
            returnValue: false,
          )
          as bool);
}
